name: permission test stuff

on: [push]


jobs:
  PlayAction:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: npm install

      - name: Update Config file in PR
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          USER_NAME: '${{secrets.USER_NAME}}'
          PASSWORD: '${{secrets.PASSWORD}}'
          PROJECTID: '${{vars.PROJECTID_B}}'
          PROJECT_SLUG: '${{vars.PROJECT_SLUG_B}}'
          PROJECT_NAME: '${{vars.PROJECT_NAME_B}}'
        run: npm run update

      - name: Update Config file in main
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          USER_NAME: '${{secrets.USER_NAME}}'
          PASSWORD: '${{secrets.PASSWORD}}'
          PROJECTID: '${{vars.PROJECTID}}'
          PROJECT_SLUG: '${{vars.PROJECT_SLUG}}'
          PROJECT_NAME: '${{vars.PROJECT_NAME}}'
        run: npm run update