name: permission test stuff

on: [push]

jobs:
  PlayAction:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install ory
        run: curl https://raw.githubusercontent.com/ory/meta/master/install.sh | sh -s ory

      - name: Move ory
        run: sudo mv ./bin/ory /usr/local/bin/

      - name: Test ory
        run: ory help

      - name: Install package
        run: npm install

      - name: Generate permission config file
        run: npm run generate
    
      - name: Update permission config file
        run:  ory update permission-config 143f18ba-304b-40d2-8894-f479b1007961 --file ./src/permission-config.json 

      - name: Remove permission config file
        run:  rm -- ./src/permission-config.json
    